### ISSUE TITLE
还是pull不下来 web页面正常

### ISSUE THREAD

**Issue by carson512** [dqzboy/Workers-Proxy-Docker#1]
docker info | grep -A 10 "Registry Mirrors"
WARNING: bridge-nf-call-iptables is disabled
 Registry Mirrors:
  https://***.fun/
 Live Restore Enabled: false

docker  pull apline
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": read tcp [2408::68b9]:47438->[2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: read: connection reset by peer

**Comment by carson512** [comment]
补充下 使用 方式一、指定代理域名下载是正常的。。

**Comment by dqzboy** [comment]
配置到 daemon.json 不行是吗？

**Comment by carson512** [comment]
> 配置到 daemon.json 不行是吗？

嗯 但是看info里又是正常的 也只配了这一个镜像 


{
  "registry-mirrors": [
	"https://*.fun/"
],
"dns":["8.8.8.8"]
}

**Comment by dqzboy** [comment]
把DNS 移除掉，走默认的宿主机的DNS呢？

**Comment by carson512** [comment]
> 把DNS 移除掉，走默认的宿主机的DNS呢？

一样的 才想的加的DNS 报错里的ip应该也是解析到了ipv6的地址。。

**Comment by dqzboy** [comment]
晚些我这边测试下 看下是不是代码修复

**Comment by carson512** [comment]
难道是docker版本的问题 附下详细的journalctl报错

docker info:
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose



11月 20 16:53:06 debian dockerd[9385]: time="2024-11-20T16:53:06.100354133+08:00" level=info msg="Attempting next endpoint for pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n" spanID=666b2ef1c995ff2e traceID=c48f7263038b8ea168e53e3375e38b51
11月 20 16:53:06 debian dockerd[9385]: time="2024-11-20T16:53:06.377318032+08:00" level=warning msg="Error getting v2 registry: Get \"https://registry-1.docker.io/v2/\": read tcp [2408::68b9]:44036->[2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: read: connection reset by peer" spanID=666b2ef1c995ff2e traceID=c48f7263038b8ea168e53e3375e38b51
11月 20 16:53:06 debian dockerd[9385]: time="2024-11-20T16:53:06.377359668+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://registry-1.docker.io/v2/\": read tcp [2408::68b9]:44036->[2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: read: connection reset by peer" spanID=666b2ef1c995ff2e traceID=c48f7263038b8ea168e53e3375e38b51
11月 20 16:53:06 debian dockerd[9385]: time="2024-11-20T16:53:06.378298880+08:00" level=error msg="Handler for POST /v1.47/images/create returned error: Get \"https://registry-1.docker.io/v2/\": read tcp [2408::68b9]:44036->[2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: read: connection reset by peer" spanID=666b2ef1c995ff2e traceID=c48f7263038b8ea168e53e3375e38b51

**Comment by dqzboy** [comment]
开头提示认证问题，应该是这个原因导致的

**Comment by carson512** [comment]
但是确实也没登录过 刚装的。。。

**Comment by dqzboy** [comment]
测试了下，没有问题可以正常pull下来
![image](https://github.com/user-attachments/assets/37c7282c-948d-4b2b-a52f-655dee035698)

**Comment by carson512** [comment]
这样看还是被重置了 导致又去默认源了

11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.885870410+08:00" level=debug msg="Calling HEAD /_ping" spanID=c68194532f1261ca traceID=85dee9336b21e3d21095ea3c841f39fb
11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.886462393+08:00" level=debug msg="Calling POST /v1.47/containers/create" spanID=fc43bde1ed37f6d9 traceID=41251293b1ced29476bd5b79233f119f
11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.886600069+08:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":false,\"AttachStdout\":true,\"Cmd\":null,\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":null,\"HostConfig\":{\"AutoRemove\":false,\"Binds\":null,\"BlkioDeviceReadBps\":[],\"BlkioDeviceReadIOps\":[],\"BlkioDeviceWriteBps\":[],\"BlkioDeviceWriteIOps\":[],\"BlkioWeight\":0,\"BlkioWeightDevice\":[],\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"CgroupnsMode\":\"\",\"ConsoleSize\":[24,80],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"DeviceCgroupRules\":null,\"DeviceRequests\":null,\"Devices\":[],\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"MaskedPaths\":null,\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NanoCpus\":0,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyPaths\":null,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":[],\"UsernsMode\":\"\",\"VolumeDriver\":\"\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"helloworld\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{\"default\":{\"Aliases\":null,\"DNSNames\":null,\"DriverOpts\":null,\"EndpointID\":\"\",\"Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"IPAMConfig\":null,\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"Links\":null,\"MacAddress\":\"\",\"NetworkID\":\"\"}}},\"OnBuild\":null,\"OpenStdin\":false,\"StdinOnce\":false,\"Tty\":false,\"User\":\"\",\"Volumes\":{},\"WorkingDir\":\"\"}" spanID=fc43bde1ed37f6d9 traceID=41251293b1ced29476bd5b79233f119f
11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.887770564+08:00" level=debug msg="Calling POST /v1.47/images/create?fromImage=helloworld&tag=latest" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.890246256+08:00" level=debug msg="hostDir: /etc/docker/certs.d/*.fun"
11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.890318593+08:00" level=debug msg="Trying to pull helloworld from https://*.fun/" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:15 debian dockerd[14356]: time="2024-11-21T10:08:15.890354850+08:00" level=debug msg="Trying to pull helloworld from https://*.fun/" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:24 debian dockerd[14356]: time="2024-11-21T10:08:24.308208128+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://*.fun/v2/library/helloworld/manifests/latest\": read tcp [2408::68b9]:54376->[2606:4700:3032::ac43:df3f]:443: read: connection reset by peer" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:24 debian dockerd[14356]: time="2024-11-21T10:08:24.308254803+08:00" level=debug msg="Trying to pull helloworld from https://registry-1.docker.io" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:24 debian dockerd[14356]: time="2024-11-21T10:08:24.308266319+08:00" level=debug msg="Trying to pull helloworld from https://registry-1.docker.io" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:25 debian dockerd[14356]: time="2024-11-21T10:08:25.356908827+08:00" level=info msg="Attempting next endpoint for pull after error: Head \"https://registry-1.docker.io/v2/library/helloworld/manifests/latest\": Get \"https://auth.docker.io/token?scope=repository%3Alibrary%2Fhelloworld%3Apull&service=registry.docker.io\": read tcp [2408::68b9]:49984->[2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: read: connection reset by peer" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab
11月 21 10:08:25 debian dockerd[14356]: time="2024-11-21T10:08:25.358091724+08:00" level=error msg="Handler for POST /v1.47/images/create returned error: Head \"https://registry-1.docker.io/v2/library/helloworld/manifests/latest\": Get \"https://auth.docker.io/token?scope=repository%3Alibrary%2Fhelloworld%3Apull&service=registry.docker.io\": read tcp [2408::68b9]:49984->[2600:1f18:2148:bc00:8d61:9b62:40aa:8bb8]:443: read: connection reset by peer" spanID=c9c13954e0f58aca traceID=f1419f35b014bd60e24756bd0b7da7ab

**Comment by dqzboy** [comment]
换个新的docker客户端试试

**Comment by carson512** [comment]
我的锅 没有 helloworld  匿了 感谢感谢
